# Generated by Django 4.1.6 on 2023-02-08 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
                ('price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('above', 'above'), ('below', 'below'), ('cross', 'cross')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
