# Generated by Django 4.1.6 on 2023-02-10 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=15),
        ),
    ]
