# Generated by Django 4.1.6 on 2023-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_symbol_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
