# Generated by Django 4.1.6 on 2023-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_last_prices', models.BooleanField(default=True, verbose_name='Update last price')),
                ('send_alert_via_telegram', models.BooleanField(default=True, verbose_name=' Send alerts via Telegram')),
                ('send_alert_via_email', models.BooleanField(default=True, verbose_name='Send alerts via E-mail')),
            ],
        ),
    ]
