# Generated by Django 4.1.6 on 2023-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coresettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
